# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.5.8
maven_group = me.juancarloscp52.spyglass_improvements
archives_name = spyglass_improvements
enabled_platforms = fabric,forge

# Mod Information
showName = Spyglass Improvements
description = Enhance Minecraft Spyglass with adjustable zoom, quick access and various spyglass overlays.
authors = juancarloscp52 (Im_JC)
license = GNU GPL 3.0
homepage = https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements
source = https://github.com/juancarloscp52/spyglass-improvements
issues = https://github.com/juancarloscp52/spyglass-improvements/issues

# Minecraft properties
minecraft_version = 1.20.1
minecraft_range_base =1.20
minecraft_range=[1.20,1.20.2)

# Dependencies
fabric_loader_version = 0.16.14
fabric_api_version = 0.92.6+1.20.1
forge_version = 1.20.1-47.4.0
forge_range=[46,)

modmenu_version=7.0.1
trinkets_version=3.7.1
curios_version=5.14.1+1.20.1
curios_range=[5.5,)