# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.5.14
maven_group = me.juancarloscp52.spyglass_improvements
archives_name = spyglass_improvements
enabled_platforms = fabric,neoforge

# Mod Information
showName = Spyglass Improvements
description = Enhance Minecraft Spyglass with adjustable zoom, quick access and various spyglass overlays.
authors = juancarloscp52 (Im_JC)
license = GNU GPL 3.0
homepage = https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements
source = https://github.com/juancarloscp52/spyglass-improvements
issues = https://github.com/juancarloscp52/spyglass-improvements/issues

# Minecraft properties
minecraft_version =26.2
minecraft_range_base =26.2
minecraft_range=[26.2,26.3)

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.154.0+26.2
neoforge_version = 26.2.0.7-beta
neoforge_range=[26.2,)

modmenu_version=19.0.0-alpha.1
trinkets_version=4.1.0-beta.2+26.2
cc_version=8.0.0
curios_version=15.0.0-beta.2+26.1.2
curios_range=[15,16)
accessories_version=1.4.0-beta+1.21.10