# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 1.5.8
maven_group = me.juancarloscp52.spyglass_improvements
archives_name = spyglass_improvements
enabled_platforms = fabric,neoforge

# Mod Information
showName = Spyglass Improvements
description = Enhance Minecraft Spyglass with adjustable zoom, quick access and various spyglass overlays.
authors = juancarloscp52 (Im_JC)
license = GNU GPL 3.0
homepage = https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements
source = https://github.com/juancarloscp52/spyglass-improvements
issues = https://github.com/juancarloscp52/spyglass-improvements/issues

# Minecraft properties
minecraft_version =1.21.3
minecraft_range_base =1.21.2
minecraft_range=[1.21.2,1.22)

# Dependencies
fabric_loader_version = 0.16.10
fabric_api_version = 0.114.0+1.21.3
neoforge_version = 21.3.66
neoforge_range=[21,)

modmenu_version=12.0.0
trinkets_version=3.10.0
cc_version=6.2.2
curios_version=9.3.1+1.21.1
curios_range=[9.0,)
accessories_version=1.2.3-beta+1.21.2