architectury {
    common rootProject.enabled_platforms.split(',')
}

repositories {
    maven {
        name = "wispForestReleases"
        url = uri("https://maven.wispforest.io/releases")
    }
    maven { url 'https://maven.su5ed.dev/releases' } //Accessories
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modCompileOnly("io.wispforest:accessories-common:${project.accessories_version}")
}
